language: node_js
node_js: stable
dist: trusty
sudo: required
group: edge
env:
  global:
  - secure: vQW2bpwgNCA9ywVokuUprcU4HSHIAiRhJN6g1Cw3kcKvEeWfJoM/WCIFfd/yZShaGuvEtF6GW5srWAUT/tST/phbei2848x5iaaRUVbk1nTrnpjVvf32zfTWw2ZVwy1j94kWzhGXmodDQziQvQNGKeitB/UlBgUkkxeUWRVC89TK8AvfxV4wgX0sNxb47btEptY8WkEb66lvz7FWJLd0483OmSV5RrCM4CJvqqkE7PfmifiHQ2qS/Ub+yOUN7vkOofXGjMVVlGA4cnWKiWBEjCq8koxlKTc+EqwuV38RmEVwqMef/5rCUZrW/U31XNiAWy4wEH3im7s0NfSV88SJT8YhgUBh+5WgGGUq0nAQfsXCxP4Nkk+LgEqCpfRB8mOdfTCEkRDz3U9xwxi5BjfIlJjQXJYXOHlT9IWniOE5OJoE2kJBRVF7KlrXzN1OURB2xk/AIIcascSPrEn98TGXZiOyaeYTv3ELX8ptanW4xofM8ItHr6OBipzI9SXhc/TBPWvCdRAxSrtw/pNOHi2P0NSk7qPuMK+pl+M5jRwDbhMJM+ZY5eWIyc/8uK9BINUoejZSHqgCI/TrKoLLl2pb62WWZckjtOaUvissqaVvydWyAWK3WCJOxdIcDbJp0hYYSHmouCBwNHpeg5HSJrY19nM9kiwh3SzCF5Lc4VsPRH8=
  - secure: skl+2Q/MEj0X2102Y84oOHsVAmx2oatHssViOWUM3ursHrh+XoD44ybW7RRZQYTYg7fuZEJC9h11hsOMpUhA4Sh2p8KkEpItM2ICyS+IANNR+N+DDYzW7KqdXqJQax47JqZy6OoRHSUvpI/djlh96f9HXDOUPJDs6CYpGAo2dq2GJKCoSrPqe3fnnbfIUocbSFDi2S0I5ZEwNHFtk8jnbkXeIhnOYuTVTC5SDKDLGDtJahgRSVgvaS2/EACd4zIWiY+81QB6n0qT8SoAyKq87Cclehouy48JXQWoZVpuod7IFQ7d3vIgIvRhPLjJe6PKXBg3EuZXYwRC9sHuFpk5scycKCUJnCz5CRV++0o+3HU4p/A6lC2QDbX7RiwPUEwHVCC6JSxYeIWm7E1abLCN1UsR6h3q+2PZ7x68bhEo7DNyhS8VttQRe8kb8F75BFtiTbw7awUlWvKLXcnK1GkNjiMEiKNLeVcv88hUe9CCkjVggJY1mmzBlra1cJAukOMGWUUAXdSD1FTdgSlP2kXgGW99AuJeUyQZz9mCcnvlOvkLHRbBJ6A6ser1Icb5yfnDojuWi1sH/k+QEYAdog/6U+FKDXNFCa8v/6Wr7+SmUfTTOJmWnchFYUlGWqY8RPKg25pVc58rxG120bJ+vmBdsw5MVM8Fi0Q4ZWnXIvJ6Hh0=
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
